import { ArrowRight, BarChart3, Code2, Hash, MessageCircle, Sparkles, Users, Zap } from 'lucide-react'
import { Link } from 'react-router-dom'
import { members, textChannels } from '../data/mockData'

function ServerWelcome() {
  return <main className="welcome-page">
    <nav className="welcome-nav"><Link className="welcome-brand" to="/"><span>V</span>Vynq</Link><div><Link to="/login">Log in</Link><Link className="nav-join" to="/register">Join the community <ArrowRight size={15} /></Link></div></nav>
    <section className="welcome-hero"><div className="hero-copy"><span className="eyebrow"><Sparkles size={13} /> VYNQ DEVELOPER COMMUNITY</span><h1>Build things<br /><em>worth sharing.</em></h1><p>A focused place for curious builders to exchange ideas, find momentum, and make better work together.</p><div className="hero-actions"><Link className="primary-action" to="/">Open the workspace <ArrowRight size={16} /></Link><span className="member-count"><Users size={16} /> 12,408 members</span></div></div><div className="hero-visual"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="hero-core"><Sparkles size={38} /></div><div className="float-card float-card-one"><Code2 size={16} /><span><strong>ship small</strong><small>make it real</small></span></div><div className="float-card float-card-two"><MessageCircle size={16} /><span><strong>42 new ideas</strong><small>in the community</small></span></div><div className="float-card float-card-three"><Zap size={16} /><span><strong>focus mode</strong><small>active now</small></span></div></div></section>
    <section className="welcome-grid"><div className="welcome-section-heading"><span>INSIDE VYNQ</span><h2>A home for the<br />in-between moments.</h2></div><div className="activity-panel"><div className="activity-header"><span>RECENT ACTIVITY</span><span className="live-dot">LIVE</span></div><div className="activity-row"><span className="activity-icon violet"><BarChart3 size={17} /></span><div><strong>Sarah shared a new dashboard study</strong><small>in #development · 8 min ago</small></div><ArrowRight size={15} /></div><div className="activity-row"><span className="activity-icon mint"><Hash size={17} /></span><div><strong>#resources is trending this week</strong><small>128 conversations · 31 new members</small></div><ArrowRight size={15} /></div><div className="activity-row"><span className="activity-icon coral"><Sparkles size={17} /></span><div><strong>Friday Build Jam starts soon</strong><small>in 2 days · 24 people are going</small></div><ArrowRight size={15} /></div></div></section>
    <section className="welcome-bottom"><div><span className="eyebrow">START EXPLORING</span><h2>Your next idea<br />might be here.</h2></div><div className="channel-pills">{textChannels.slice(0, 4).map((channel) => <span key={channel}><Hash size={14} />{channel}</span>)}</div><div className="online-stat"><strong>{members.filter((member) => member.online).length}</strong><span>online right now</span></div></section>
  </main>
}

export default ServerWelcome
